---
- name: Failed output
  hosts: local
  connection: local
  gather_facts: false
  
  tasks:
    - name: Fail task when the command error output prints FAILED
      command: ./fail-command
      register: command_result
      failed_when: "'FAILED' in command_result.stdout"
