---
- name: Overriding the changed result
  hosts: local
  connection: local
  gather_facts: false
  become: true
  become_user: root
  
  tasks:
    - name: clear yum cache
      command: yum clean metadata
      register: yum_clear
      changed_when: '"\n0 metadata files removed" not in yum_clear.stdout'

    - debug: var=yum_clear

    - name: pwd command
      shell: pwd
      changed_when: false
