---
- name: Test ansible play
  hosts: localhost
  connection: local
  gather_facts: false
  
  tasks:
    - name: Unvault the password file
      copy:
        src: "{{ playbook_dir }}/pass"
        dest: "{{ playbook_dir }}/password"
